dist: xenial

language: node_js
node_js:
  - "12"

# Install yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --non-interactive

script:
  - yarn run build

#after_success:

# Monitor only these branches
branches:
  only:
    - master

# $HOME/.cache/yarn
cache:
  yarn: true

# https://docs.travis-ci.com/user/deployment/pages/
#before_deploy:

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch:  'gh-pages'
  local-dir:  'dist/ng-todo-app'
  on:
    branch: 'master'
